version: '3.8'

services:
  web:
    build: .
    ports:
      - 8000:8000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - web
    links:
      - web:web
